apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: product-manager
    version: 1.2.3
    environment: development
  annotations:
    description: This is core application of this company, please double check your changes
spec:
  containers:
    - name: nginx
      image: nginx:1.23.3-alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3