apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
spec:
  nodeSelector:
    gpu: 'true'
  containers:
    - name: nginx
      image: nginx:1.23.3-alpine
      ports:
        - containerPort: 80
