apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: product-manager
    version: 1.2.3
    environment: development
  annotations:
    description: This is core application of this company, please double check your changes
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80