apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    # matchLabels:
    #   app: data-guardian
    matchExpressions:
      - key: app
        operator: In
        values:
          - data-guardian
      - key: env
        operator: In
        values:
          - prod
          - dev
          - sandbox
  template:
    metadata:
      name: nginx
      labels:
        app: data-guardian
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.3-alpine
          ports:
            - containerPort: 80